import { Client } from '@/redux/slices/clientSlice';

// Dữ liệu mẫu cho màn hình clients
export const mockClients: Client[] = [
  {
    ID: '1',
    companyName: 'Enterprise Corporation',
    shortName: 'EnterCorp',
    clientNumber: 'CL-001',
    clientTypeCode: 'CORP',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Corporate',
    productCategory: 'Banking',
    status: 'active',
    contractsCount: 3,
    cityzenship: 'Vietnam',
    dateOpen: '2022-01-15',
  },
  {
    ID: '2',
    companyName: 'Tech Solutions Ltd',
    shortName: 'TechSol',
    clientNumber: 'CL-002',
    clientTypeCode: 'TECH',
    reasonCode: 'RC002',
    reason: 'Service Expansion',
    institutionCode: 'INST02',
    branch: 'Hanoi Branch',
    clientCategory: 'SME',
    productCategory: 'Technology',
    status: 'inactive',
    contractsCount: 1,
    cityzenship: 'Singapore',
    dateOpen: '2022-03-22',
  },
  {
    ID: '3',
    companyName: 'Global Trading Co',
    shortName: 'GTC',
    clientNumber: 'CL-003',
    clientTypeCode: 'TRAD',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Corporate',
    productCategory: 'Trading',
    status: 'active',
    contractsCount: 5,
    cityzenship: 'United States',
    dateOpen: '2022-05-10',
  },
  {
    ID: '4',
    companyName: 'Financial Services Inc',
    shortName: 'FinServ',
    clientNumber: 'CL-004',
    clientTypeCode: 'FIN',
    reasonCode: 'RC003',
    reason: 'Portfolio Management',
    institutionCode: 'INST03',
    branch: 'Da Nang Branch',
    clientCategory: 'Financial',
    productCategory: 'Investment',
    status: 'active',
    contractsCount: 7,
    cityzenship: 'Canada',
    dateOpen: '2022-07-05',
  },
  {
    ID: '5',
    companyName: 'Healthcare Solutions',
    shortName: 'HealthSol',
    clientNumber: 'CL-005',
    clientTypeCode: 'HEALTH',
    reasonCode: 'RC002',
    reason: 'Service Expansion',
    institutionCode: 'INST02',
    branch: 'Hanoi Branch',
    clientCategory: 'Healthcare',
    productCategory: 'Medical',
    status: 'inactive',
    contractsCount: 2,
    cityzenship: 'Australia',
    dateOpen: '2022-08-12',
  },
  {
    ID: '6',
    companyName: 'Retail Group',
    shortName: 'RetGroup',
    clientNumber: 'CL-006',
    clientTypeCode: 'RET',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Retail',
    productCategory: 'Consumer',
    status: 'active',
    contractsCount: 4,
    cityzenship: 'Japan',
    dateOpen: '2022-09-20',
  },
  {
    ID: '7',
    companyName: 'Manufacturing Industries',
    shortName: 'ManInd',
    clientNumber: 'CL-007',
    clientTypeCode: 'MAN',
    reasonCode: 'RC004',
    reason: 'Supply Chain Management',
    institutionCode: 'INST04',
    branch: 'Can Tho Branch',
    clientCategory: 'Manufacturing',
    productCategory: 'Industrial',
    status: 'active',
    contractsCount: 6,
    cityzenship: 'South Korea',
    dateOpen: '2022-10-15',
  },
  {
    ID: '8',
    companyName: 'Logistics Partners',
    shortName: 'LogPart',
    clientNumber: 'CL-008',
    clientTypeCode: 'LOG',
    reasonCode: 'RC003',
    reason: 'Portfolio Management',
    institutionCode: 'INST03',
    branch: 'Da Nang Branch',
    clientCategory: 'Logistics',
    productCategory: 'Transportation',
    status: 'inactive',
    contractsCount: 0,
    cityzenship: 'Thailand',
    dateOpen: '2022-11-08',
  },
  {
    ID: '9',
    companyName: 'Energy Corporation',
    shortName: 'EnergyCorp',
    clientNumber: 'CL-009',
    clientTypeCode: 'ENGY',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Energy',
    productCategory: 'Utilities',
    status: 'active',
    contractsCount: 2,
    cityzenship: 'Malaysia',
    dateOpen: '2022-12-01',
  },
  {
    ID: '10',
    companyName: 'Hospitality Group',
    shortName: 'HospGroup',
    clientNumber: 'CL-010',
    clientTypeCode: 'HOSP',
    reasonCode: 'RC002',
    reason: 'Service Expansion',
    institutionCode: 'INST02',
    branch: 'Hanoi Branch',
    clientCategory: 'Hospitality',
    productCategory: 'Tourism',
    status: 'active',
    contractsCount: 8,
    cityzenship: 'Vietnam',
    dateOpen: '2023-01-15',
  }
];

// Tạo cấu trúc response giống API
export const mockClientResponse = {
  data: {
    clients: mockClients,
    totalItems: mockClients.length,
    totalPages: Math.ceil(mockClients.length / 10),
    currentPage: 1,
    itemsPerPage: 10
  }
}; 