export interface Customer {
  id: string;
  companyName: string;
  shortName: string;
  clientNumber: string;
  clientTypeCode: string;
  reasonCode: string;
  reason: string;
  institutionCode: string;
  branch: string;
  clientCategory: string;
  productCategory: string;
  status: 'active' | 'inactive';
  contractsCount: number;
}

export type FilterCriteria = 'Most Contracts' | 'Latest Customers' | 'Oldest Customers' | null;
export type StatusFilter = 'all' | 'active' | 'inactive';

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    companyName: 'Enterprise Corporation',
    shortName: 'EnterCorp',
    clientNumber: 'CL-001',
    clientTypeCode: 'CORP',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Corporate',
    productCategory: 'Banking',
    status: 'active',
    contractsCount: 3,
  },
  {
    id: '2',
    companyName: 'Tech Solutions Ltd',
    shortName: 'TechSol',
    clientNumber: 'CL-002',
    clientTypeCode: 'TECH',
    reasonCode: 'RC002',
    reason: 'Service Expansion',
    institutionCode: 'INST02',
    branch: 'Hanoi Branch',
    clientCategory: 'SME',
    productCategory: 'Technology',
    status: 'inactive',
    contractsCount: 1,
  },
  {
    id: '3',
    companyName: 'Global Trading Co',
    shortName: 'GTC',
    clientNumber: 'CL-003',
    clientTypeCode: 'TRAD',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Corporate',
    productCategory: 'Trading',
    status: 'active',
    contractsCount: 5,
  },
  {
    id: '4',
    companyName: 'Retail Chain Inc',
    shortName: 'RetChain',
    clientNumber: 'CL-004',
    clientTypeCode: 'RETL',
    reasonCode: 'RC003',
    reason: 'Partnership',
    institutionCode: 'INST03',
    branch: 'Danang Branch',
    clientCategory: 'Retail',
    productCategory: 'Commerce',
    status: 'active',
    contractsCount: 2,
  },
  {
    id: '5',
    companyName: 'Financial Services Group',
    shortName: 'FinServ',
    clientNumber: 'CL-005',
    clientTypeCode: 'FIN',
    reasonCode: 'RC001',
    reason: 'New Business',
    institutionCode: 'INST01',
    branch: 'HCM Branch',
    clientCategory: 'Financial',
    productCategory: 'Banking',
    status: 'inactive',
    contractsCount: 0,
  },
  {
    id: '6',
    companyName: 'Innovatech Ltd',
    shortName: 'InnoTech',
    clientNumber: 'CL-006',
    clientTypeCode: 'TECH',
    reasonCode: 'RC006',
    reason: 'New Market Entry',
    institutionCode: 'INST06',
    branch: 'Hanoi Branch',
    clientCategory: 'Technology',
    productCategory: 'Software',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '7',
    companyName: 'Healthcare Solutions Co',
    shortName: 'HealthSol',
    clientNumber: 'CL-007',
    clientTypeCode: 'HLT',
    reasonCode: 'RC007',
    reason: 'New Market Entry',
    institutionCode: 'INST07',
    branch: 'HCM Branch',
    clientCategory: 'Healthcare',
    productCategory: 'Medical',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '8',
    companyName: 'Education Institute',
    shortName: 'EduInst',
    clientNumber: 'CL-008',
    clientTypeCode: 'EDU',
    reasonCode: 'RC008',
    reason: 'New Market Entry',
    institutionCode: 'INST08',
    branch: 'Hanoi Branch',
    clientCategory: 'Education',
    productCategory: 'Training',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '9',
    companyName: 'Entertainment Group',
    shortName: 'Entertain',
    clientNumber: 'CL-009',
    clientTypeCode: 'ENT',
    reasonCode: 'RC009',
    reason: 'New Market Entry',
    institutionCode: 'INST09',
    branch: 'HCM Branch',
    clientCategory: 'Entertainment',
    productCategory: 'Media',
    status: 'inactive',
    contractsCount: 0,
  },
  {
    id: '10',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction', 
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '11',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '12',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '13',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '14',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '15',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  },
  {
    id: '16',
    companyName: 'Construction Company',
    shortName: 'Constr',
    clientNumber: 'CL-010',
    clientTypeCode: 'CON',
    reasonCode: 'RC010',
    reason: 'New Market Entry',
    institutionCode: 'INST10',
    branch: 'Hanoi Branch',
    clientCategory: 'Construction',
    productCategory: 'Construction',
    status: 'active',
    contractsCount: 0,
  }
];

export const DEFAULT_FORM_DATA: Omit<Customer, 'id'> = {
  companyName: '',
  shortName: '',
  clientNumber: '',
  clientTypeCode: '',
  reasonCode: '',
  reason: '',
  institutionCode: '',
  branch: '',
  clientCategory: '',
  productCategory: '',
  status: 'active',
  contractsCount: 0
}; 